# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=4000)),
                ('question_type', models.CharField(blank=True, choices=[('python', 'python'), ('django', 'django')], default='python', max_length=60)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
                ('choices', models.CharField(blank=True, help_text='first answer is the correct one, answers will be randomized when question is asked', max_length=600, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True, verbose_name='0-10, from easiest to hardest')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='playground.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
