# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_auto_20160714_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='version',
            field=models.CharField(blank=True, choices=[('python2.7', 'python2.7'), ('python3.5', 'python3.5'), ('django1.9', 'django1.9')], default='python3.5', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('python', 'python'), ('django', 'django'), ('vim', 'vim')], default='python', max_length=60),
        ),
    ]
